"""doctor availability

Revision ID: 2be0f5a67b3e
Revises: e27253f5b719
Create Date: 2026-06-18 19:21:05.103484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be0f5a67b3e'
down_revision: Union[str, Sequence[str], None] = 'e27253f5b719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('consultation_fee', sa.Float(), nullable=True))
    op.add_column('doctors', sa.Column('available_from', sa.Time(), nullable=True))
    op.add_column('doctors', sa.Column('available_to', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'available_to')
    op.drop_column('doctors', 'available_from')
    op.drop_column('doctors', 'consultation_fee')
    # ### end Alembic commands ###
