"""medical record improvements

Revision ID: c803ff2cdf2d
Revises: 5393c2d1ad85
Create Date: 2026-06-19 09:23:46.348979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c803ff2cdf2d'
down_revision: Union[str, Sequence[str], None] = '5393c2d1ad85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'created_at')
    # ### end Alembic commands ###
